version: '3'

services:
  elastic:
    container_name: elastic
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    environment:
      - node.name=es01
      - cluster.initial_master_nodes=es01
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks: 
      - esnet
    
  kibana:
    container_name: kibana
    restart: always
    image: docker.elastic.co/kibana/kibana:7.3.1
    environment:
      ELASTICSEARCH_URL: http://elastic:9200
      ELASTICSEARCH_USERNAME: username
      ELASTICSEARCH_PASSWORD: password
    networks:
      - esnet
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    depends_on: 
      - elastic

volumes:
  esdata:
    driver: local

networks:
  esnet:

